title: MRTD Kit
logo: /assets/img/logo_270_transparent.png
description: MRTD Kit is a framework for working with machine readable travel documents.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
